openapi: 3.0.0
info:
  title: Staff Student Management API
  version: 1.0.0
servers:
  - url: http://localhost:3000

tags:
  - name: Student
    description: Student EndPoint
  - name: Staff
    description: Staff EndPoint

paths:
  /staff:
    $ref: "./paths/staff.yaml"

components:
  schemas:
    $ref: "./schemas/schemas.yaml"
